source 'http://rubygems.org'

gem 'watir'
gem 'rspec'
gem 'rspec-core'
gem 'require_all'
gem 'chromedriver-helper'
gem 'watir-scroll'
gem 'rest-client'
gem 'rspec-retry'
gem 'byebug'
gem 'nokogiri'
gem 'rspec_html_reporter'
gem 'colorize'
gem 'json'
